[project]
name = "rag-faq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Usama Bashir", email = "buttuxama@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "ollama>=0.6.3",
    "openai>=3.22.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
rag-faq = "rag_faq:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
